name: Build and push Docker image (amd64, arm64 to hub.docker.com and ghcr.io)

on:
  workflow_dispatch: # allow manual trigger
  # https://github.com/orgs/community/discussions/26276
  push: # on every branch, but not for PRs from forks?
    paths:
      - '**'
      - '!README.md'
      - '!.github/**'
      - '.github/workflows/docker.yml'
  pull_request: # includes PRs from forks but only triggers on creation, not pushes?
    branches:
      - "main" # only PRs against main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set environment variables
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "NOW=$(date -R)" >> $GITHUB_ENV # date -Iseconds; date +'%Y-%m-%dT%H:%M:%S'
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        # if: ${{ secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          build-args: |
            COMMIT=${{ github.sha }}
            BRANCH=${{ env.BRANCH }}
            NOW=${{ env.NOW }}
          platforms: linux/amd64,linux/arm64 # ,linux/arm/v7
          tags: |
            voglerr/free-games-claimer:latest
            ghcr.io/vogler/free-games-claimer:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
